#!/usr/bin/env bash

. ".env" || { echo " !! Failed to source .env.devdenv file" >&2 ; exit 1; }
. "$DEVDENV_PATH/.init-host.sh" || { echo " !! Failed to source $DEVDENV_PATH/.init-host.sh" >&2 ; exit 1; }

requireExplicitSuccess false

# ./devdenv -vvv php-apache indocker set-document-root.sh  /app

serviceName="$1"
command="$2"

shift 2

case "$command" in
	indocker)
		scriptName="$1"
		shift

		docker-compose exec "$serviceName" "$BUILD_SCRIPTS_MOUNT_POINT/$serviceName/build/indocker/$scriptName" "$@"
	;;
	*)
		echo "Unknown command $command" >&2
		exit 1
esac

