version: '2.0'

services:

  php-apache:
    user: ${RUN_AS_UID}:${RUN_AS_GID}
    build: 
        context: ${SERVICES_PATH}/php-apache/build
        args:
          documentRoot: ${PHP_APACHE__DOCUMENT_ROOT}
    volumes:
    - ${PHP_APACHE__BIND_DIRECTORY}:/app
    networks:
      app_net:
        ipv4_address: ${BASE_NET}.2

