version: '2.0'

services:

  php-apache:
    user: ${RUN_AS_UID}:${RUN_AS_GID}
    build: 
        context: ${SERVICES_PATH}/php-apache/build
        dockerfile: Dockerfile-${PHP_APACHE__PHP_VERSION}
        args:
          documentRoot: ${PHP_APACHE__DOCUMENT_ROOT}
          runAsUid: ${RUN_AS_UID}
    volumes:
    - ${PHP_APACHE__BIND_DIRECTORY}:/app
    networks:
      app_net:
        ipv4_address: ${PHP_APACHE__IP}

