version: '2.0'

services:

  php-apache:
    user: ${RUN_AS_UID}:${RUN_AS_GID}
    build: 
        context: ${DOCKER_COMPOSE_CONF_PATH}/php-apache
        args:
          documentRoot: ${PHP_APACHE__DOCUMENT_ROOT}
    volumes:
    - ./src:/app
    networks:
      app_net:
        ipv4_address: ${BASE_NET}.2

  mysql:
    build:
      context: ${DOCKER_COMPOSE_CONF_PATH}/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=project
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: ${BASE_NET}.3

volumes:
  mysql-volume:


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${BASE_NET}.0/${BASE_NET_MASK}
        gateway: ${BASE_NET}.1

