version: '2.0'

services:

  php-apache:
    user: ${RUN_AS_UID}:${RUN_AS_GID}
    build: 
        context: ./dev-stuff/docker-compose/php-apache
    volumes:
    - ./src:/app
    networks:
      app_net:
        ipv4_address: ${BASE_NET}.2

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${BASE_NET}.0/${BASE_NET_MASK}
        gateway: ${BASE_NET}.1

