version: '2.0'

services:

  mysql:
    build:
      context: ${SERVICES_PATH}/mysql/build
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=project
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: ${BASE_NET}.${MYSQL__IP}

volumes:
  mysql-volume:


